/*
NotificationAPI

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SenderPostBodySlackMetadataEntitiesInnerExternalRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderPostBodySlackMetadataEntitiesInnerExternalRef{}

// SenderPostBodySlackMetadataEntitiesInnerExternalRef Reference used to identify an entity within the developer's system.
type SenderPostBodySlackMetadataEntitiesInnerExternalRef struct {
	Id   string  `json:"id"`
	Type *string `json:"type,omitempty"`
}

type _SenderPostBodySlackMetadataEntitiesInnerExternalRef SenderPostBodySlackMetadataEntitiesInnerExternalRef

// NewSenderPostBodySlackMetadataEntitiesInnerExternalRef instantiates a new SenderPostBodySlackMetadataEntitiesInnerExternalRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderPostBodySlackMetadataEntitiesInnerExternalRef(id string) *SenderPostBodySlackMetadataEntitiesInnerExternalRef {
	this := SenderPostBodySlackMetadataEntitiesInnerExternalRef{}
	this.Id = id
	return &this
}

// NewSenderPostBodySlackMetadataEntitiesInnerExternalRefWithDefaults instantiates a new SenderPostBodySlackMetadataEntitiesInnerExternalRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderPostBodySlackMetadataEntitiesInnerExternalRefWithDefaults() *SenderPostBodySlackMetadataEntitiesInnerExternalRef {
	this := SenderPostBodySlackMetadataEntitiesInnerExternalRef{}
	return &this
}

// GetId returns the Id field value
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) SetType(v string) {
	o.Type = &v
}

func (o SenderPostBodySlackMetadataEntitiesInnerExternalRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderPostBodySlackMetadataEntitiesInnerExternalRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *SenderPostBodySlackMetadataEntitiesInnerExternalRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSenderPostBodySlackMetadataEntitiesInnerExternalRef := _SenderPostBodySlackMetadataEntitiesInnerExternalRef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSenderPostBodySlackMetadataEntitiesInnerExternalRef)

	if err != nil {
		return err
	}

	*o = SenderPostBodySlackMetadataEntitiesInnerExternalRef(varSenderPostBodySlackMetadataEntitiesInnerExternalRef)

	return err
}

type NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef struct {
	value *SenderPostBodySlackMetadataEntitiesInnerExternalRef
	isSet bool
}

func (v NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef) Get() *SenderPostBodySlackMetadataEntitiesInnerExternalRef {
	return v.value
}

func (v *NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef) Set(val *SenderPostBodySlackMetadataEntitiesInnerExternalRef) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderPostBodySlackMetadataEntitiesInnerExternalRef(val *SenderPostBodySlackMetadataEntitiesInnerExternalRef) *NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef {
	return &NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef{value: val, isSet: true}
}

func (v NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderPostBodySlackMetadataEntitiesInnerExternalRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
