/*
NotificationAPI

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
	"fmt"
)

// GetTemplatesResponse struct for GetTemplatesResponse
type GetTemplatesResponse struct {
	GetInappNotificationsResponseNotificationsInnerTemplateAnyOf        *GetInappNotificationsResponseNotificationsInnerTemplateAnyOf
	ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf *[]GetInappNotificationsResponseNotificationsInnerTemplateAnyOf
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetTemplatesResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into GetInappNotificationsResponseNotificationsInnerTemplateAnyOf
	err = json.Unmarshal(data, &dst.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf)
	if err == nil {
		jsonGetInappNotificationsResponseNotificationsInnerTemplateAnyOf, _ := json.Marshal(dst.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf)
		if string(jsonGetInappNotificationsResponseNotificationsInnerTemplateAnyOf) == "{}" { // empty struct
			dst.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf = nil
		} else {
			return nil // data stored in dst.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf, return on the first match
		}
	} else {
		dst.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf = nil
	}

	// try to unmarshal JSON data into ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf
	err = json.Unmarshal(data, &dst.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf)
	if err == nil {
		jsonArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf, _ := json.Marshal(dst.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf)
		if string(jsonArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf) == "{}" { // empty struct
			dst.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf = nil
		} else {
			return nil // data stored in dst.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf, return on the first match
		}
	} else {
		dst.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetTemplatesResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetTemplatesResponse) MarshalJSON() ([]byte, error) {
	if src.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf != nil {
		return json.Marshal(&src.GetInappNotificationsResponseNotificationsInnerTemplateAnyOf)
	}

	if src.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf != nil {
		return json.Marshal(&src.ArrayOfGetInappNotificationsResponseNotificationsInnerTemplateAnyOf)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableGetTemplatesResponse struct {
	value *GetTemplatesResponse
	isSet bool
}

func (v NullableGetTemplatesResponse) Get() *GetTemplatesResponse {
	return v.value
}

func (v *NullableGetTemplatesResponse) Set(val *GetTemplatesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplatesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplatesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplatesResponse(val *GetTemplatesResponse) *NullableGetTemplatesResponse {
	return &NullableGetTemplatesResponse{value: val, isSet: true}
}

func (v NullableGetTemplatesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplatesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
