/*
NotificationAPI

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
	"fmt"
)

// checks if the TemplatePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplatePostRequest{}

// TemplatePostRequest struct for TemplatePostRequest
type TemplatePostRequest struct {
	TemplateId           string `json:"templateId"`
	AdditionalProperties map[string]interface{}
}

type _TemplatePostRequest TemplatePostRequest

// NewTemplatePostRequest instantiates a new TemplatePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatePostRequest(templateId string) *TemplatePostRequest {
	this := TemplatePostRequest{}
	this.TemplateId = templateId
	return &this
}

// NewTemplatePostRequestWithDefaults instantiates a new TemplatePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatePostRequestWithDefaults() *TemplatePostRequest {
	this := TemplatePostRequest{}
	return &this
}

// GetTemplateId returns the TemplateId field value
func (o *TemplatePostRequest) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *TemplatePostRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *TemplatePostRequest) SetTemplateId(v string) {
	o.TemplateId = v
}

func (o TemplatePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplatePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["templateId"] = o.TemplateId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TemplatePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"templateId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplatePostRequest := _TemplatePostRequest{}

	err = json.Unmarshal(data, &varTemplatePostRequest)

	if err != nil {
		return err
	}

	*o = TemplatePostRequest(varTemplatePostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "templateId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemplatePostRequest struct {
	value *TemplatePostRequest
	isSet bool
}

func (v NullableTemplatePostRequest) Get() *TemplatePostRequest {
	return v.value
}

func (v *NullableTemplatePostRequest) Set(val *TemplatePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatePostRequest(val *TemplatePostRequest) *NullableTemplatePostRequest {
	return &NullableTemplatePostRequest{value: val, isSet: true}
}

func (v NullableTemplatePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
