/*
NotificationAPI

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"encoding/json"
)

// checks if the NotificationPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationPatchRequest{}

// NotificationPatchRequest struct for NotificationPatchRequest
type NotificationPatchRequest struct {
	Title         *string                                     `json:"title,omitempty"`
	Channels      []ChannelsEnum                              `json:"channels,omitempty"`
	Enabled       *bool                                       `json:"enabled,omitempty"`
	Deduplication *GetNotificationsResponseInnerDeduplication `json:"deduplication,omitempty"`
	Throttling    *GetNotificationsResponseInnerThrottling    `json:"throttling,omitempty"`
	Retention     *float32                                    `json:"retention,omitempty"`
	Options       *GetNotificationsResponseInnerOptions       `json:"options,omitempty"`
}

// NewNotificationPatchRequest instantiates a new NotificationPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationPatchRequest() *NotificationPatchRequest {
	this := NotificationPatchRequest{}
	return &this
}

// NewNotificationPatchRequestWithDefaults instantiates a new NotificationPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationPatchRequestWithDefaults() *NotificationPatchRequest {
	this := NotificationPatchRequest{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *NotificationPatchRequest) SetTitle(v string) {
	o.Title = &v
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetChannels() []ChannelsEnum {
	if o == nil || IsNil(o.Channels) {
		var ret []ChannelsEnum
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetChannelsOk() ([]ChannelsEnum, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []ChannelsEnum and assigns it to the Channels field.
func (o *NotificationPatchRequest) SetChannels(v []ChannelsEnum) {
	o.Channels = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *NotificationPatchRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetDeduplication returns the Deduplication field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetDeduplication() GetNotificationsResponseInnerDeduplication {
	if o == nil || IsNil(o.Deduplication) {
		var ret GetNotificationsResponseInnerDeduplication
		return ret
	}
	return *o.Deduplication
}

// GetDeduplicationOk returns a tuple with the Deduplication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetDeduplicationOk() (*GetNotificationsResponseInnerDeduplication, bool) {
	if o == nil || IsNil(o.Deduplication) {
		return nil, false
	}
	return o.Deduplication, true
}

// HasDeduplication returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasDeduplication() bool {
	if o != nil && !IsNil(o.Deduplication) {
		return true
	}

	return false
}

// SetDeduplication gets a reference to the given GetNotificationsResponseInnerDeduplication and assigns it to the Deduplication field.
func (o *NotificationPatchRequest) SetDeduplication(v GetNotificationsResponseInnerDeduplication) {
	o.Deduplication = &v
}

// GetThrottling returns the Throttling field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetThrottling() GetNotificationsResponseInnerThrottling {
	if o == nil || IsNil(o.Throttling) {
		var ret GetNotificationsResponseInnerThrottling
		return ret
	}
	return *o.Throttling
}

// GetThrottlingOk returns a tuple with the Throttling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetThrottlingOk() (*GetNotificationsResponseInnerThrottling, bool) {
	if o == nil || IsNil(o.Throttling) {
		return nil, false
	}
	return o.Throttling, true
}

// HasThrottling returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasThrottling() bool {
	if o != nil && !IsNil(o.Throttling) {
		return true
	}

	return false
}

// SetThrottling gets a reference to the given GetNotificationsResponseInnerThrottling and assigns it to the Throttling field.
func (o *NotificationPatchRequest) SetThrottling(v GetNotificationsResponseInnerThrottling) {
	o.Throttling = &v
}

// GetRetention returns the Retention field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetRetention() float32 {
	if o == nil || IsNil(o.Retention) {
		var ret float32
		return ret
	}
	return *o.Retention
}

// GetRetentionOk returns a tuple with the Retention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetRetentionOk() (*float32, bool) {
	if o == nil || IsNil(o.Retention) {
		return nil, false
	}
	return o.Retention, true
}

// HasRetention returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasRetention() bool {
	if o != nil && !IsNil(o.Retention) {
		return true
	}

	return false
}

// SetRetention gets a reference to the given float32 and assigns it to the Retention field.
func (o *NotificationPatchRequest) SetRetention(v float32) {
	o.Retention = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *NotificationPatchRequest) GetOptions() GetNotificationsResponseInnerOptions {
	if o == nil || IsNil(o.Options) {
		var ret GetNotificationsResponseInnerOptions
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationPatchRequest) GetOptionsOk() (*GetNotificationsResponseInnerOptions, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *NotificationPatchRequest) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given GetNotificationsResponseInnerOptions and assigns it to the Options field.
func (o *NotificationPatchRequest) SetOptions(v GetNotificationsResponseInnerOptions) {
	o.Options = &v
}

func (o NotificationPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Deduplication) {
		toSerialize["deduplication"] = o.Deduplication
	}
	if !IsNil(o.Throttling) {
		toSerialize["throttling"] = o.Throttling
	}
	if !IsNil(o.Retention) {
		toSerialize["retention"] = o.Retention
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

type NullableNotificationPatchRequest struct {
	value *NotificationPatchRequest
	isSet bool
}

func (v NullableNotificationPatchRequest) Get() *NotificationPatchRequest {
	return v.value
}

func (v *NullableNotificationPatchRequest) Set(val *NotificationPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationPatchRequest(val *NotificationPatchRequest) *NullableNotificationPatchRequest {
	return &NullableNotificationPatchRequest{value: val, isSet: true}
}

func (v NullableNotificationPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
