/*
NotificationAPI

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SenderPostBodySlackMetadataEntitiesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderPostBodySlackMetadataEntitiesInner{}

// SenderPostBodySlackMetadataEntitiesInner struct for SenderPostBodySlackMetadataEntitiesInner
type SenderPostBodySlackMetadataEntitiesInner struct {
	// Entity type (e.g., 'slack#/entities/task', 'slack#/entities/file').
	EntityType string `json:"entity_type"`
	// Schema for the given entity type.
	EntityPayload map[string]interface{}                              `json:"entity_payload"`
	ExternalRef   SenderPostBodySlackMetadataEntitiesInnerExternalRef `json:"external_ref"`
	// URL used to identify an entity within the developer's system.
	Url string `json:"url"`
	// The exact URL posted in the source message. Required in metadata passed to `chat.unfurl`.
	AppUnfurlUrl *string `json:"app_unfurl_url,omitempty"`
}

type _SenderPostBodySlackMetadataEntitiesInner SenderPostBodySlackMetadataEntitiesInner

// NewSenderPostBodySlackMetadataEntitiesInner instantiates a new SenderPostBodySlackMetadataEntitiesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderPostBodySlackMetadataEntitiesInner(entityType string, entityPayload map[string]interface{}, externalRef SenderPostBodySlackMetadataEntitiesInnerExternalRef, url string) *SenderPostBodySlackMetadataEntitiesInner {
	this := SenderPostBodySlackMetadataEntitiesInner{}
	this.EntityType = entityType
	this.EntityPayload = entityPayload
	this.ExternalRef = externalRef
	this.Url = url
	return &this
}

// NewSenderPostBodySlackMetadataEntitiesInnerWithDefaults instantiates a new SenderPostBodySlackMetadataEntitiesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderPostBodySlackMetadataEntitiesInnerWithDefaults() *SenderPostBodySlackMetadataEntitiesInner {
	this := SenderPostBodySlackMetadataEntitiesInner{}
	return &this
}

// GetEntityType returns the EntityType field value
func (o *SenderPostBodySlackMetadataEntitiesInner) GetEntityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInner) GetEntityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityType, true
}

// SetEntityType sets field value
func (o *SenderPostBodySlackMetadataEntitiesInner) SetEntityType(v string) {
	o.EntityType = v
}

// GetEntityPayload returns the EntityPayload field value
func (o *SenderPostBodySlackMetadataEntitiesInner) GetEntityPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.EntityPayload
}

// GetEntityPayloadOk returns a tuple with the EntityPayload field value
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInner) GetEntityPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.EntityPayload, true
}

// SetEntityPayload sets field value
func (o *SenderPostBodySlackMetadataEntitiesInner) SetEntityPayload(v map[string]interface{}) {
	o.EntityPayload = v
}

// GetExternalRef returns the ExternalRef field value
func (o *SenderPostBodySlackMetadataEntitiesInner) GetExternalRef() SenderPostBodySlackMetadataEntitiesInnerExternalRef {
	if o == nil {
		var ret SenderPostBodySlackMetadataEntitiesInnerExternalRef
		return ret
	}

	return o.ExternalRef
}

// GetExternalRefOk returns a tuple with the ExternalRef field value
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInner) GetExternalRefOk() (*SenderPostBodySlackMetadataEntitiesInnerExternalRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExternalRef, true
}

// SetExternalRef sets field value
func (o *SenderPostBodySlackMetadataEntitiesInner) SetExternalRef(v SenderPostBodySlackMetadataEntitiesInnerExternalRef) {
	o.ExternalRef = v
}

// GetUrl returns the Url field value
func (o *SenderPostBodySlackMetadataEntitiesInner) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SenderPostBodySlackMetadataEntitiesInner) SetUrl(v string) {
	o.Url = v
}

// GetAppUnfurlUrl returns the AppUnfurlUrl field value if set, zero value otherwise.
func (o *SenderPostBodySlackMetadataEntitiesInner) GetAppUnfurlUrl() string {
	if o == nil || IsNil(o.AppUnfurlUrl) {
		var ret string
		return ret
	}
	return *o.AppUnfurlUrl
}

// GetAppUnfurlUrlOk returns a tuple with the AppUnfurlUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderPostBodySlackMetadataEntitiesInner) GetAppUnfurlUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AppUnfurlUrl) {
		return nil, false
	}
	return o.AppUnfurlUrl, true
}

// HasAppUnfurlUrl returns a boolean if a field has been set.
func (o *SenderPostBodySlackMetadataEntitiesInner) HasAppUnfurlUrl() bool {
	if o != nil && !IsNil(o.AppUnfurlUrl) {
		return true
	}

	return false
}

// SetAppUnfurlUrl gets a reference to the given string and assigns it to the AppUnfurlUrl field.
func (o *SenderPostBodySlackMetadataEntitiesInner) SetAppUnfurlUrl(v string) {
	o.AppUnfurlUrl = &v
}

func (o SenderPostBodySlackMetadataEntitiesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderPostBodySlackMetadataEntitiesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entity_type"] = o.EntityType
	toSerialize["entity_payload"] = o.EntityPayload
	toSerialize["external_ref"] = o.ExternalRef
	toSerialize["url"] = o.Url
	if !IsNil(o.AppUnfurlUrl) {
		toSerialize["app_unfurl_url"] = o.AppUnfurlUrl
	}
	return toSerialize, nil
}

func (o *SenderPostBodySlackMetadataEntitiesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_type",
		"entity_payload",
		"external_ref",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSenderPostBodySlackMetadataEntitiesInner := _SenderPostBodySlackMetadataEntitiesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSenderPostBodySlackMetadataEntitiesInner)

	if err != nil {
		return err
	}

	*o = SenderPostBodySlackMetadataEntitiesInner(varSenderPostBodySlackMetadataEntitiesInner)

	return err
}

type NullableSenderPostBodySlackMetadataEntitiesInner struct {
	value *SenderPostBodySlackMetadataEntitiesInner
	isSet bool
}

func (v NullableSenderPostBodySlackMetadataEntitiesInner) Get() *SenderPostBodySlackMetadataEntitiesInner {
	return v.value
}

func (v *NullableSenderPostBodySlackMetadataEntitiesInner) Set(val *SenderPostBodySlackMetadataEntitiesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderPostBodySlackMetadataEntitiesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderPostBodySlackMetadataEntitiesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderPostBodySlackMetadataEntitiesInner(val *SenderPostBodySlackMetadataEntitiesInner) *NullableSenderPostBodySlackMetadataEntitiesInner {
	return &NullableSenderPostBodySlackMetadataEntitiesInner{value: val, isSet: true}
}

func (v NullableSenderPostBodySlackMetadataEntitiesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderPostBodySlackMetadataEntitiesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
