/*
NotificationAPI

Internal API for notification delivery and management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingram

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetNotificationsResponseInnerThrottling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNotificationsResponseInnerThrottling{}

// GetNotificationsResponseInnerThrottling struct for GetNotificationsResponseInnerThrottling
type GetNotificationsResponseInnerThrottling struct {
	Max     float32  `json:"max"`
	Period  float32  `json:"period"`
	Unit    string   `json:"unit"`
	Forever bool     `json:"forever"`
	Scope   []string `json:"scope"`
}

type _GetNotificationsResponseInnerThrottling GetNotificationsResponseInnerThrottling

// NewGetNotificationsResponseInnerThrottling instantiates a new GetNotificationsResponseInnerThrottling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNotificationsResponseInnerThrottling(max float32, period float32, unit string, forever bool, scope []string) *GetNotificationsResponseInnerThrottling {
	this := GetNotificationsResponseInnerThrottling{}
	this.Max = max
	this.Period = period
	this.Unit = unit
	this.Forever = forever
	this.Scope = scope
	return &this
}

// NewGetNotificationsResponseInnerThrottlingWithDefaults instantiates a new GetNotificationsResponseInnerThrottling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNotificationsResponseInnerThrottlingWithDefaults() *GetNotificationsResponseInnerThrottling {
	this := GetNotificationsResponseInnerThrottling{}
	return &this
}

// GetMax returns the Max field value
func (o *GetNotificationsResponseInnerThrottling) GetMax() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Max
}

// GetMaxOk returns a tuple with the Max field value
// and a boolean to check if the value has been set.
func (o *GetNotificationsResponseInnerThrottling) GetMaxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Max, true
}

// SetMax sets field value
func (o *GetNotificationsResponseInnerThrottling) SetMax(v float32) {
	o.Max = v
}

// GetPeriod returns the Period field value
func (o *GetNotificationsResponseInnerThrottling) GetPeriod() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Period
}

// GetPeriodOk returns a tuple with the Period field value
// and a boolean to check if the value has been set.
func (o *GetNotificationsResponseInnerThrottling) GetPeriodOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Period, true
}

// SetPeriod sets field value
func (o *GetNotificationsResponseInnerThrottling) SetPeriod(v float32) {
	o.Period = v
}

// GetUnit returns the Unit field value
func (o *GetNotificationsResponseInnerThrottling) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *GetNotificationsResponseInnerThrottling) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *GetNotificationsResponseInnerThrottling) SetUnit(v string) {
	o.Unit = v
}

// GetForever returns the Forever field value
func (o *GetNotificationsResponseInnerThrottling) GetForever() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Forever
}

// GetForeverOk returns a tuple with the Forever field value
// and a boolean to check if the value has been set.
func (o *GetNotificationsResponseInnerThrottling) GetForeverOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Forever, true
}

// SetForever sets field value
func (o *GetNotificationsResponseInnerThrottling) SetForever(v bool) {
	o.Forever = v
}

// GetScope returns the Scope field value
func (o *GetNotificationsResponseInnerThrottling) GetScope() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *GetNotificationsResponseInnerThrottling) GetScopeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope, true
}

// SetScope sets field value
func (o *GetNotificationsResponseInnerThrottling) SetScope(v []string) {
	o.Scope = v
}

func (o GetNotificationsResponseInnerThrottling) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNotificationsResponseInnerThrottling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["max"] = o.Max
	toSerialize["period"] = o.Period
	toSerialize["unit"] = o.Unit
	toSerialize["forever"] = o.Forever
	toSerialize["scope"] = o.Scope
	return toSerialize, nil
}

func (o *GetNotificationsResponseInnerThrottling) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"max",
		"period",
		"unit",
		"forever",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetNotificationsResponseInnerThrottling := _GetNotificationsResponseInnerThrottling{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetNotificationsResponseInnerThrottling)

	if err != nil {
		return err
	}

	*o = GetNotificationsResponseInnerThrottling(varGetNotificationsResponseInnerThrottling)

	return err
}

type NullableGetNotificationsResponseInnerThrottling struct {
	value *GetNotificationsResponseInnerThrottling
	isSet bool
}

func (v NullableGetNotificationsResponseInnerThrottling) Get() *GetNotificationsResponseInnerThrottling {
	return v.value
}

func (v *NullableGetNotificationsResponseInnerThrottling) Set(val *GetNotificationsResponseInnerThrottling) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNotificationsResponseInnerThrottling) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNotificationsResponseInnerThrottling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNotificationsResponseInnerThrottling(val *GetNotificationsResponseInnerThrottling) *NullableGetNotificationsResponseInnerThrottling {
	return &NullableGetNotificationsResponseInnerThrottling{value: val, isSet: true}
}

func (v NullableGetNotificationsResponseInnerThrottling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNotificationsResponseInnerThrottling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
